# Generated by Django 5.2.3 on 2025-08-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_images_product_new_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='images',
        ),
        migrations.AddField(
            model_name='product',
            name='include',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
