# Generated by Django 5.2.3 on 2025-08-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_category_images_product_include'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.JSONField(),
        ),
    ]
