# Generated by Django 5.2.3 on 2025-08-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categoryImage',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
