# Generated by Django 5.2.3 on 2025-08-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_product_include_include'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
